export const ErrorCode = {
  // Auth - General
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",

  // Auth - Tokens
  AUTH_ACCESS_TOKEN_INVALID: "AUTH_ACCESS_TOKEN_INVALID",
  AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",
  AUTH_REFRESH_TOKEN_REQUIRED: "AUTH_REFRESH_TOKEN_REQUIRED",

  // Auth - Google
  AUTH_GOOGLE_NOT_CONFIGURED: "AUTH_GOOGLE_NOT_CONFIGURED",
  AUTH_GOOGLE_TOKEN_INVALID: "AUTH_GOOGLE_TOKEN_INVALID",

  // Auth - Credentials
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_PASSWORD_ALREADY_SET: "AUTH_PASSWORD_ALREADY_SET",
  AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",

  // Auth - Verification / Reset
  AUTH_VERIFICATION_TOKEN_INVALID: "AUTH_VERIFICATION_TOKEN_INVALID",
  AUTH_RESET_TOKEN_INVALID: "AUTH_RESET_TOKEN_INVALID",

  // Auth - Sessions
  AUTH_SESSION_NOT_FOUND: "AUTH_SESSION_NOT_FOUND",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",

  // Courses
  COURSE_NOT_FOUND: "COURSE_NOT_FOUND",
  COURSE_FORBIDDEN: "COURSE_FORBIDDEN",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // System
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
